name: Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Dependencies
        run: |
          python -m pip install -U pip
          python -m pip install nox
      - name: Tests
        run: python -m nox --non-interactive --session tests
        env:
          GIT_AUTHOR_NAME: "Author Name"
          GIT_AUTHOR_EMAIL: "author@git.email"
